### ISSUE TITLE
Memory leak on front-end?

### ISSUE THREAD

**Issue by wezm** [feedbin/feedbin#702] opened 2023-04-10 02:54 UTC
I've recently noticed that Feedbin seems to be accumulating about a gigabyte of memory per-day in my browser.

This is after about 7 days uptime on my machine:

<img width="1250" alt="Screenshot from 2023-04-09 10-34-56-cropped" src="https://user-images.githubusercontent.com/21787/230815838-9bf408cb-04d2-4ec1-9a90-26e9fb57d7e0.png">

Yesterday I noticed that my machine was almost out of RAM and swap and I took that screenshot. I quit Firefox and restarted it and today, about 24 hours later it's now back up to 1Gb:

<img width="1246" alt="Screenshot from 2023-04-10 12-48-40" src="https://user-images.githubusercontent.com/21787/230816001-0ca18b7d-d9e0-4c06-a4dc-bddc013d2a36.png">

**System details:**

OS: Arch Linux
Browser: Firefox 111.0.1

**Comment by markcellus** [comment] 2023-04-10 10:11
It may be worth ruling out the browser itself. Does this happen on any other browser? Asking because certain browsers (especially Firefox) quite frequently have bugs with newer APIs that Feedbin may use, which could be the cause.

**Comment by benubois** [comment] 2023-04-13 12:36
Hi @wezm,

Thanks for reporting this. I can't reproduce anything using Firefox 112 on macOS. I would expect memory usage to be affected by what/how much you're subscribed to and it's possible it could also depend on the OS.

Are you using Feedbin the entire time or does it happen just from being open in a background tab?

It would be great if you could share two heap snapshots. If they're taken a few hours or a day apart it should be possible to see where the growth is happening.

You can [follow these instructions](https://firefox-source-docs.mozilla.org/devtools-user/memory/basic_operations/) for how to do this. You can email the snapshots to support@feedbin.com.

Ben

**Comment by wezm** [comment] 2023-04-14 00:21
Looks like it's happening in Chromium too. I've taken initial heap snapshots in Chromium and Firefox and will take the subsequent ones at the end of the day.

<img width="865" alt="Screenshot from 2023-04-14 10-15-04" src="https://user-images.githubusercontent.com/21787/231910330-724ffa7f-f2fa-4a93-8493-46499c88e258.png">

**Comment by wezm** [comment] 2023-04-14 05:17
I sent through the Firefox heap snapshots to the support email address. . Chromium seems to be incapable of processing the larger one. It takes it then a spinner just goes forever (presumably it would eventually finish). Weirdly the Chromium process was up to about 4Gb of memory from 10am to 3pm.

Here's a preview of Firefox, `about:memory` was saying that it was up to about 900Mb of use:

<img width="1247" alt="Screenshot from 2023-04-14 15-13-17" src="https://user-images.githubusercontent.com/21787/231947430-a42878ec-e269-4ef4-af4f-201e37e3750f.png">

**Comment by wezm** [comment] 2023-07-07 00:37
Sorry to bump this but just wanted to chime in and mention this is still an issue for me. Is there anything else I can provide to help find a fix. I understand if this is not a widespread issue and therefore a low priority—I can continue to make sure I refresh my Feedbin tab every day or so.

**Comment by wezm** [comment] 2023-07-22 05:31
No sure if you changed anything but it appears that this is no longer happening. I'm now on Firefox 115, if nothing changed on the Feedbin end then maybe they fixed something in Firefox.

**Comment by benubois** [comment] 2023-07-22 10:22
@wezm,

That’s great! I had spent some time looking into it, but not gotten anywhere. 

Closing for now.

**Comment by wezm** [comment] 2023-08-14 01:40
Unfortunately it appears that I was wrong. Doesn't seem to be a widespread issue since I don't see anyone else complaining so may as well leave this closed and I'll look into Firefox extensions that can reload the tab every day or so.

<img width="1201" alt="Screenshot from 2023-08-14 11-38-03" src="https://github.com/feedbin/feedbin/assets/21787/6a5b8d71-a2c5-4b91-8110-e66301ea1612">

**Comment by Zegnat** [comment] 2023-08-27 18:56
I have noticed this too, and it has definitely not been fixed any time recently. Just today my tab had grown to 4 GB of memory in `about:processes`. Just closing the tab and opening feedbin.com anew loaded the tab in at only 132 MB. 

It grows really slow, and I have had a hard time to figure out what causes the growth. I am not sure if it is something that just happens over time because of data refreshes in the background, or if it has to do with how much I am interacting with the page.

**Comment by wezm** [comment] 2023-09-28 02:59
I just noticed that this is also happening on my (rarely used Mac).

<img width="1280" alt="Screen Shot 2023-09-28 at 12 58 51 pm" src="https://github.com/feedbin/feedbin/assets/21787/3c43a484-5617-4f3c-8026-ad0a35f5c29c">

Browser: 109.0.1
OS: macOS 11.7.1 (Intel)

**Comment by benubois** [comment] 2023-10-11 19:09
@wezm I looked into this a bit more and was able to find something reproducible. 

It seems like replacing a bunch of elements leaks memory. Feedbin's auto-update process polls for any changes to the subscription list/unread count and it also replaces many elements. 

I wasn't able to get to the bottom of why that causes a leak, but did manage to [cut down on the amount of times the feed list needed to be replaced](https://github.com/feedbin/feedbin/commit/5c989ce2fa93ba3fda79f8be9500b7883bf2e289).

Would you mind reloading Feedbin and reporting back how your memory usage looks in a day or two?

Thanks!

**Comment by wezm** [comment] 2023-10-11 21:50
Yep no problem. I'll leave it open today and report back tomorrow

**Comment by wezm** [comment] 2023-10-11 21:57
Oh also one way elements can leak/be retained is if they have JavaScript event handlers attached to them. I think when the elements are removed from the DOM the event handlers need to be removed too, not sure if that's what's happening here.

**Comment by benubois** [comment] 2023-10-11 22:08
Yeah, came across that too. However, Feedbin almost exclusively listens to `document` with many selectors, so there are no listeners bound directly to elements I think.

**Comment by wezm** [comment] 2023-10-12 23:39
After having a Feedbin tab open all day yesterday Firefox says it's using 883Mb RAM. After a refresh it went down to 150Mb. So it's perhaps not growing as quickly but still seems to grow over a day.

**Comment by wezm** [comment] 2024-08-11 07:11
Just bumping this as I was wondering why my laptop was being slow:

![image](https://github.com/user-attachments/assets/7876a999-9233-4cdc-8a50-2ec890926ffc)

Note that this is a completely different machine (and OS) than my original report:

- Windows 11 ARM
- Firefox 128.0.3 (64-bit)

**Comment by benubois** [comment] 2024-08-11 09:03
Could you upload a [memory report]( https://firefox-source-docs.mozilla.org/performance/memory/about_colon_memory.html)?

**Comment by wezm** [comment] 2024-08-11 10:08
I reloaded the tab to free up memory but I'll generate one when it's grown a bit again.

**Comment by wezm** [comment] 2024-08-13 01:24
@benubois I've emailed the memory report to support@

**Comment by benubois** [comment] 2024-08-14 15:16
Thanks @wezm!

I think I've made some progress on this. Would you mind reloading and checking back in tomorrow to see if the situation is also improved for you?

**Comment by wezm** [comment] 2024-08-14 22:51
Great, thank you! Happy to do whatever I can to help out. I'll report back at the end of the work day today.

**Comment by wezm** [comment] 2024-08-15 10:47
After my workday the Feedbin tab is showing 8GB in the Firefox `about:processes` view. I did reload at the start of the day so it should have pulled any changes you made.

**Comment by benubois** [comment] 2024-08-16 11:32
Ok! I was able to find and fix more potential issues. Let's give it another try.

**Comment by wezm** [comment] 2024-08-21 00:04
I think the recent changes may have done the trick! Memory use seems to be consistently low and stable now.

**Comment by benubois** [comment] 2024-09-16 15:28
@wezm Great! Appreciate your help tracking this down.

**Closed by benubois** 2024-09-16 15:28 UTC
