### ISSUE TITLE
Add web share support

### ISSUE THREAD

**Issue by revanmj** [feedbin/feedbin#589] opened 2020-12-30 14:45 UTC
Since Feedbin can already be installed as PWA, it would be great if it also supported [Web Share API](https://www.w3.org/TR/web-share/) (so we can invoke system sharing menu from it on OSes that have one like Android or Windows 10).

**Comment by benubois** [comment] 2020-12-30 18:40
On the list! (Dupe of #568).

**Comment by revanmj** [comment] 2020-12-30 18:42
The way I understood it, #568 is for sending URLs to Feedbin from other apps. 

Mine is about sending URLs from Feedbin to other apps. That's why I created separate issue :)

**Comment by benubois** [comment] 2020-12-30 18:44
You're right! Got confused by them sharing the "Web Share" prefix.

How do you imagine this working? Feedbin already has a sharing system. Would it replace that or show up as an additional option on [Share & Save](https://feedbin.com/settings/sharing)?

**Comment by revanmj** [comment] 2020-12-30 18:49
Additional option, like on Twitter (that potentially could be enabled/disabled via settings like all the others)

(translating menu items from screenshot below from top to bottom: "Send in DM", "Add to bookmarks", "Copy tweet URL", "Share tweet via ...")

![Zrzut ekranu 2020-12-30 194658](https://user-images.githubusercontent.com/1777618/103374507-0d368400-4ad8-11eb-81f0-7eae8935d9ff.png)

**Comment by endquote** [comment] 2021-01-24 16:09
Using the OS sharing feature on both web and desktop would be great. Then Feedbin wouldn't have to support specific services, and the user would be able to share to anything they have installed.

**Comment by diminutivesloop** [comment] 2021-02-26 01:29
This would be great to have. Currently the built-in share to Instapaper functionality doesn’t support saving to a specific folder but web share would provide that functionality for free via the Instapaper browser extension.

**Closed** 2021-04-14 17:33 UTC

**Comment by revanmj** [comment] 2021-04-14 17:58
Works great in Chrome on Windows 10 and when installed as PWA on Android, thanks!
